# Generated by Django 5.2.6 on 2025-09-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='page',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
